import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import ThemeRegistry from "./ThemeRegistry";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const sessionCookie = (await cookieStore).get("session")?.value;
  const isLoggedIn = !!sessionCookie;

  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <Header isLoggedIn={isLoggedIn} />
          <main style={{ paddingTop: "80px" }}>{children}</main>
        </ThemeRegistry>
      </body>
    </html>
  );
}